import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  celestiaSidebar: [
    {
      type: 'html',
      value: '<img src="https://docs.celestia.org/logo-light.svg" class="sub-logo" alt="Sponsor" />', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    'celestia/intro',
    {
      type: 'category',
      label: 'Gettings Started',
      collapsible: false,
      collapsed: false,
      items: ['celestia/quickstart'],
    },
    {
      type: 'category',
      label: 'Validator Node',
      collapsible: false,
      collapsed: false,
      items: [
        'celestia/validator/register-validator',
        'celestia/validator/upgrade-validator',
        'celestia/validator/quick-commands',

      ],
    },
    {
      type: 'category',
      label: 'Bridge Node',
      collapsible: false,
      collapsed: false,
      items: [
        'celestia/bridge-da-node/zfs-storage-optional',
        'celestia/bridge-da-node/running-bridge-node',
        'celestia/bridge-da-node/upgrading',
        'celestia/bridge-da-node/monitoring',

      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
